'use strict';

/* SMR Hub — ampliación del banco de preguntas (fase 6)
   Añade preguntas a los tests existentes y crea los tests de Virtualización,
   Mantenimiento y Ofimática. Cada pregunta declara difficulty
   (Básica/Intermedia/Avanzada), topic (estadísticas por tema),
   relatedResource (recomendación al fallar) y explain. Opcional:
   wrongWhy = { índiceOpción: 'por qué es incorrecta' }.
   Incluye un validador que avisa en consola si hay preguntas sin explicar,
   sin dificultad o con respuestas fuera de rango. */

(function () {
  const D = window.SMR_DATA;
  if (!D || !Array.isArray(D.tests)) return;

  /* ---------- Preguntas para tests existentes ---------- */

  const EXTRA_QUESTIONS = {
    't-redes': [
      { q: '¿Cuántos hosts útiles ofrece un prefijo /28?', options: ['12', '14', '16', '30'], correct: 1, difficulty: 'Intermedia', topic: 'Subnetting', relatedResource: 'r-red-subnet-intermedio', explain: '2^(32-28) − 2 = 16 − 2 = 14 hosts; los otros dos son red y broadcast.', wrongWhy: { 0: 'Sería 2^(32-29) − 2 = 14/2... no: 12 no sale de ningún prefijo estándar aquí.', 2: '16 son las direcciones totales del bloque, sin restar red y broadcast.', 3: '30 hosts corresponde a un /27.' } },
      { q: 'Un equipo con IP 10.0.0.37/29. ¿Cuál es su dirección de red?', options: ['10.0.0.32', '10.0.0.34', '10.0.0.35', '10.0.0.40'], correct: 0, difficulty: 'Intermedia', topic: 'Subnetting', relatedResource: 'r-red-subnet-intermedio', explain: '/29 salta de 8: bloques .0, .8, .16, .24, .32… La .37 cae en el bloque .32 (broadcast .39).' },
      { q: '¿Cuál es el broadcast de 172.16.10.77/26?', options: ['172.16.10.95', '172.16.10.127', '172.16.10.63', '172.16.10.79'], correct: 1, difficulty: 'Intermedia', topic: 'Subnetting', relatedResource: 'r-red-subnet-intermedio', explain: '/26 salta de 64: bloques .0, .64, .128… La .77 cae en el bloque .64, cuyo broadcast es .127.', wrongWhy: { 0: '.95 sería el broadcast de un bloque /27 (.64-.95).', 2: '.63 es el broadcast del bloque .0-.63, anterior al de la .77.', 3: '.79 no es límite de bloque /26 alguno.' } },
      { q: 'Necesitas 100 hosts en una subred. ¿El prefijo más eficiente es…', options: ['/24', '/25', '/26', '/27'], correct: 1, difficulty: 'Intermedia', topic: 'Subnetting', relatedResource: 'r-red-vlsm-avanzado', explain: '/25 ofrece 126 hosts ≥ 100. /26 solo da 62 (no basta) y /24 desperdicia 154 direcciones.', wrongWhy: { 0: '/24 (254) funcionaría pero desperdicia la mitad del espacio.', 2: '/26 da 62 hosts: insuficiente para 100.', 3: '/27 da 30: muy por debajo de lo pedido.' } },
      { q: '¿Cuántas subredes /28 caben en un /24?', options: ['8', '14', '16', '32'], correct: 2, difficulty: 'Avanzada', topic: 'Subnetting', relatedResource: 'r-red-vlsm-avanzado', explain: '2^(28−24) = 16 subredes de 16 direcciones cada una.', wrongWhy: { 0: '8 sería 2^(27−24): un /27.', 1: '14 es el número de hosts útiles de una subred /28, no el número de subredes /28 que caben en un /24.', 3: '32 saldrían de un /29.' } },
      { q: 'En una trama Ethernet, el campo FCS sirve para…', options: ['cifrar los datos', 'detectar errores de transmisión', 'indicar el protocolo de capa 3', 'controlar el flujo'], correct: 1, difficulty: 'Intermedia', topic: 'Ethernet', relatedResource: 'r-red-ethernet-mac', explain: 'El FCS contiene un CRC que permite detectar tramas corruptas (se descartan, no se corrigen).', wrongWhy: { 0: 'El cifrado no existe en la trama Ethernet clásica.', 2: 'El protocolo de capa 3 va en el campo Type.', 3: 'El control de flujo es TCP, no Ethernet.' } },
      { q: 'Dos PCs conectados al mismo switch pero en VLANs distintas se envían un broadcast. ¿Qué ocurre?', options: ['Cada VLAN recibe solo su broadcast', 'El broadcast llega a ambos por ser el mismo switch', 'El switch lo descarta siempre', 'Lo reenvía al router automáticamente'], correct: 0, difficulty: 'Intermedia', topic: 'VLAN', relatedResource: 'r-red-vlan', explain: 'Cada VLAN es un dominio de difusión independiente: los broadcasts no cruzan entre VLANs aunque compartan hardware.', wrongWhy: { 1: 'Compartir hardware no comparte dominio de difusión: eso es justo lo que separa una VLAN.', 2: 'No se descarta: se entrega dentro de su VLAN.', 3: 'El router no reenvía broadcasts de capa 2.' } },
      { q: 'Para que dos VLANs se comuniquen necesitas…', options: ['un switch de más puertos', 'un dispositivo de capa 3', 'cableado Cat6a', 'duplicar el ancho de banda'], correct: 1, difficulty: 'Básica', topic: 'VLAN', relatedResource: 'r-red-vlan', explain: 'Las VLANs están aisladas a propósito; solo un router o un switch de capa 3 decide qué tráfico pasa entre ellas.' },
      { q: '¿Qué hace PAT con las conexiones salientes de una red doméstica?', options: ['Asigna una IP pública fija a cada equipo', 'Comparte una IP pública usando puertos distintos por conexión', 'Cifra el tráfico hacia internet', 'Reparto el ancho de banda por igual'], correct: 1, difficulty: 'Intermedia', topic: 'NAT', relatedResource: 'r-red-nat-routing', explain: 'PAT (NAT de sobrecarga) mantiene una tabla IP:puerto interno ↔ IP:puerto público para multiplexar todas las conexiones sobre una única IP pública.' },
      { q: 'Un router recibe un paquete para 10.0.5.7 y tiene rutas 10.0.0.0/16 y 10.0.5.0/24. ¿Cuál usa?', options: ['/16 por tener menor métrica', '/24 por ser más específica', 'Carga balanceada entre ambas', 'La primera que aprendió'], correct: 1, difficulty: 'Avanzada', topic: 'Routing', relatedResource: 'r-red-nat-routing', explain: 'La tabla de rutas elige el prefijo más largo (más específico): /24 gana a /16 independientemente de las métricas.' },
      { q: 'Un equipo responde a ping por IP pero no abre www.google.com. ¿Qué capa revisas?', options: ['Capa física', 'Gateway', 'DNS', 'Firewall del destino'], correct: 2, difficulty: 'Intermedia', topic: 'Diagnóstico', relatedResource: 'r-red-servicios-dns', explain: 'Conectividad IP correcta + fallo de nombres = problema de resolución DNS (nslookup lo confirma).' },
      { q: 'El orden correcto del método de ping escalonado es…', options: ['127.0.0.1 → propia IP → gateway → 8.8.8.8 → dominio', 'dominio → 8.8.8.8 → gateway → propia IP', 'gateway → 127.0.0.1 → dominio → 8.8.8.8', 'propia IP → dominio → 127.0.0.1 → gateway'], correct: 0, difficulty: 'Intermedia', topic: 'Diagnóstico', relatedResource: 'r-red-icmp-diagnostico', explain: 'Se avanza del anillo local hacia fuera: pila TCP/IP, tarjeta, red local, internet y por último la resolución de nombres.' },
      { q: '¿Qué tipo de registro DNS asocia www.ejemplo.es con su IPv6?', options: ['A', 'AAAA', 'CNAME', 'MX'], correct: 1, difficulty: 'Básica', topic: 'DNS', relatedResource: 'r-red-servicios-dns', explain: 'AAAA es el registro de dirección IPv6; A es el equivalente para IPv4 y CNAME define alias.' },
      { q: 'Una consulta DNS normal viaja por…', options: ['UDP/53', 'TCP/53 siempre', 'UDP/68', 'TCP/25'], correct: 0, difficulty: 'Básica', topic: 'DNS', relatedResource: 'r-red-servicios-dns', explain: 'Las consultas normales van por UDP/53 por eficiencia; TCP/53 queda para respuestas grandes y transferencias de zona.' },
      { q: '¿Qué dirección IPv6 es una link-local?', options: ['2001:db8::1', 'fe80::1', 'ff02::1', '::1'], correct: 1, difficulty: 'Intermedia', topic: 'IPv6', relatedResource: 'r-red-ipv6', explain: 'fe80::/10 es el rango link-local que toda interfaz IPv6 posee; ff02::1 es multicast y ::1 es loopback.' },
      { q: 'En la dirección 2001:0db8:0000:0000:0000:ff00:0042:8329, ¿cuál es la forma abreviada correcta?', options: ['2001:db8::ff00:42:8329', '2001:db8::ff00::42:8329', '2001:db8:0:0:0:ff00:42:8329 con ::', '2001:db8:ff00:42:8329'], correct: 0, difficulty: 'Intermedia', topic: 'IPv6', relatedResource: 'r-red-ipv6', explain: 'Los ceros iniciales de cada grupo se eliminan y un solo bloque de ceros se comprime con :: (una única vez).' },
      { q: '¿Qué documento define el comportamiento de los enlaces /31 punto a punto?', options: ['RFC 1918', 'RFC 3021', 'RFC 791', 'IEEE 802.1Q'], correct: 1, difficulty: 'Avanzada', topic: 'Subnetting', relatedResource: 'r-red-vlsm-avanzado', explain: 'La RFC 3021 permite usar /31 en enlaces punto a punto sin reservar dirección de red ni broadcast.' },
      { q: 'Un switch aprende qué puerto usa para cada MAC mediante…', options: ['consultas ARP propias', 'la MAC origen de las tramas recibidas', 'el servidor DHCP', 'broadcasts del router'], correct: 1, difficulty: 'Básica', topic: 'Ethernet', relatedResource: 'r-red-ethernet-mac', explain: 'Cuando una trama entra, el switch registra su MAC origen y el puerto de entrada: así construye su tabla de direcciones.' },
      { q: 'Un AP (punto de acceso) conectado al switch con un SSID "Invitados" aislado es correcto si…', options: ['el AP crea su propia subred con DHCP', 'el AP solo reenvía a la VLAN configurada y el aislamiento lo hacen VLAN/firewall', 'se desactiva el DHCP del router principal', 'se usa WEP para los invitados'], correct: 1, difficulty: 'Avanzada', topic: 'VLAN', relatedResource: 'r-red-vlan', explain: 'El AP en modo acceso entrega el tráfico etiquetado o sin etiquetar a una VLAN; el aislamiento real lo dan VLAN + reglas de firewall, no el AP.' },
      { q: '¿Qué medio elegirías para unir dos edificios separados 500 m en exterior?', options: ['UTP Cat6a', 'Coaxial RG-58', 'Fibra monomodo', 'UTP Cat5e con repetidor cada 100 m'], correct: 2, difficulty: 'Intermedia', topic: 'Medios', relatedResource: 'r-red-topologia', explain: 'UTP limita a 100 m; la fibra inmuniza a interferencias y alcanza cientos de metros o kilómetros sin repetidores.' },
      { q: 'Un tramo UTP de 140 m entre dos switches del mismo edificio…', options: ['funciona a 1 Gbps sin problemas', 'funciona solo a 100 Mbps', 'supera el límite de 100 m: habrá errores o enlace caído', 'requiere STP obligatoriamente'], correct: 2, difficulty: 'Básica', topic: 'Medios', relatedResource: 'r-red-topologia', explain: 'El estándar Ethernet por par trenzado fija 100 m máximo por tramo; más allá, la atenuación corrompe la señal.' },
      { q: '¿Cuál es la wildcard de un /27?', options: ['0.0.0.31', '0.0.0.63', '255.255.255.224', '0.0.0.15'], correct: 0, difficulty: 'Intermedia', topic: 'Subnetting', relatedResource: 'r-red-subnet-intermedio', explain: 'Máscara /27 = 255.255.255.224; la wildcard es su complemento: 0.0.0.31 (32 − 1).' },
      { q: 'En VLSM, ¿por qué se asignan primero las subredes mayores?', options: ['Porque consumen más CPU del router', 'Porque los bloques grandes necesitan alineación y, si van al final, no caben', 'Porque el DHCP las reparte antes', 'Porque las VLANs lo exigen'], correct: 1, difficulty: 'Avanzada', topic: 'VLSM', relatedResource: 'r-red-vlsm-avanzado', explain: 'Un bloque /26 solo puede empezar en múltiplos de 64; si lo dejas para el final, el hueco restante rara vez estará alineado y no cabrá.' },
      { q: '192.168.0.224/30, ¿qué hosts asignables tiene?', options: ['.225 y .226', '.224 y .225', '.226 y .227', 'solo .225'], correct: 0, difficulty: 'Intermedia', topic: 'VLSM', relatedResource: 'r-red-vlsm-avanzado', explain: 'Bloque .224-.227: .224 es red, .227 es broadcast y quedan .225 y .226 asignables.' },
      { q: 'Tracert muestra un salto con "Request timed out" pero los siguientes sí responden. ¿Qué significa?', options: ['La conexión está corta en ese salto', 'Ese router no responde al ICMP pero sí encamina', 'El TTL era insuficiente', 'Hay un bucle de rutas'], correct: 1, difficulty: 'Avanzada', topic: 'Diagnóstico', relatedResource: 'r-red-icmp-diagnostico', explain: 'Muchos routers limitan o ignoran ICMP hacia su propia dirección mientras siguen reenviando paquetes: el camino continúa.' },
      { q: 'El DHCP de tu red entrega gateway 192.168.2.1 a equipos en 192.168.1.0/24. ¿Síntoma esperable?', options: ['Todo funciona igual', 'Navegan pero no ven la impresora', 'No salen de la red local (sin internet)', 'Reciben IP duplicada'], correct: 2, difficulty: 'Avanzada', topic: 'Diagnóstico', relatedResource: 'r-red-nat-routing', explain: 'El gateway debe estar en la propia subred: con un gateway de otra subred los paquetes hacia internet no encuentran su primer salto.' },
      { q: '¿Qué comando muestra la tabla de rutas en Windows?', options: ['route print', 'ip route show', 'netstat -r only en Linux', 'arp -a'], correct: 0, difficulty: 'Intermedia', topic: 'Diagnóstico', relatedResource: 'r-red-icmp-diagnostico', explain: 'route print (o netstat -r) muestra la tabla de rutas de Windows; ip route show es el equivalente en Linux.' }
    ],
    't-sistemas': [
      { q: '¿Qué permisos corresponden a 640 en Linux?', options: ['rw-r-----', 'rwxr-xr-x', 'rw-rw-r--', 'rwx------'], correct: 0, difficulty: 'Intermedia', topic: 'Permisos', relatedResource: 'r-so-fs-permisos', explain: '6 = rw (dueño), 4 = r (grupo), 0 = nada (otros).', wrongWhy: { 1: 'Ese es 755.', 2: 'Ese es 664.', 3: 'Ese es 700.' } },
      { q: 'Para que un directorio sea "atravesable" pero no listable, sus permisos serían…', options: ['r--', '--x', 'r-x', 'rw-'], correct: 1, difficulty: 'Avanzada', topic: 'Permisos', relatedResource: 'r-so-fs-permisos', explain: 'El bit x en directorios permite atravesarlo (acceder a rutas conocidas dentro) sin poder listar su contenido (eso es r).' },
      { q: '¿Qué ocurre si cambias los permisos de un archivo en un disco exFAT?', options: ['Se aplican y persisten', 'exFAT no soporta permisos POSIX: no persisten', 'Solo persisten para el dueño', 'Se aplican solo en Linux'], correct: 1, difficulty: 'Intermedia', topic: 'Permisos', relatedResource: 'r-so-fs-permisos', explain: 'FAT32 y exFAT no almacenan permisos ni propietarios; NTFS y ext4 sí.' },
      { q: 'Un equipo tiene 8 GB de RAM y el uso de disco está al 100% con el sistema paginando. ¿Qué fenómeno es?', options: ['Thrashing', 'BSOD', 'Fallo de POST', 'Memory leak del kernel solamente'], correct: 0, difficulty: 'Intermedia', topic: 'Memoria', relatedResource: 'r-so-memoria', explain: 'Thrashing: el sistema pasa más tiempo intercambiando páginas que trabajando; síntoma clásico de RAM insuficiente.' },
      { q: 'La diferencia esencial entre proceso y hilo es que el hilo…', options: ['tiene su propio espacio de direcciones', 'comparte la memoria de su proceso', 'no puede ser planificado', 'solo existe en Linux'], correct: 1, difficulty: 'Intermedia', topic: 'Procesos', relatedResource: 'r-so-memoria', explain: 'Los hilos de un proceso comparten su memoria y recursos; cada proceso tiene un espacio aislado.' },
      { q: 'El orden correcto del arranque es…', options: ['POST → bootloader → kernel → servicios', 'kernel → POST → bootloader → servicios', 'POST → kernel → bootloader → login', 'bootloader → POST → kernel → BIOS'], correct: 0, difficulty: 'Básica', topic: 'Arranque', relatedResource: 'r-so-arranque', explain: 'El firmware verifica hardware (POST), entrega al bootloader, que carga el kernel, que a su vez arranca los servicios.' },
      { q: '"Operating System not found" tras el logo del fabricante indica…', options: ['fallo de POST', 'el firmware no encuentra bootloader o disco arrancable', 'RAM insuficiente', 'fallo del monitor'], correct: 1, difficulty: 'Intermedia', topic: 'Arranque', relatedResource: 'r-so-arranque', explain: 'El POST pasó (hay logo); el firmware no encuentra cargador: orden de arranque, disco detectado o BCD/GRUB.' },
      { q: 'Secure Boot es…', options: ['un antivirus de Windows', 'verificación de firma del bootloader en UEFI', 'un tipo de partición', 'el modo seguro de Windows'], correct: 1, difficulty: 'Básica', topic: 'Arranque', relatedResource: 'r-so-arranque', explain: 'Secure Boot impide ejecutar cargadores no firmados por claves de confianza en sistemas UEFI.' },
      { q: '¿Qué comando muestra los servicios en ejecución en Linux con systemd?', options: ['services list', 'systemctl list-units --type=service --state=running', 'ps aux | grep service', 'service --status-all solo'], correct: 1, difficulty: 'Intermedia', topic: 'Servicios', relatedResource: 'r-so-powershell-bash', explain: 'systemctl list-units --type=service --state=running lista servicios activos; service --status-all es el método legacy.' },
      { q: 'En PowerShell, Get-Process | Sort-Object WS -Descending | Select-Object -First 5…', options: ['borra los 5 procesos con más memoria', 'muestra los 5 procesos con más memoria de trabajo', 'ordena por CPU', 'exporta a CSV'], correct: 1, difficulty: 'Intermedia', topic: 'PowerShell', relatedResource: 'r-so-powershell-bash', explain: 'WS es el conjunto de trabajo (memoria física); el pipeline ordena y toma los 5 primeros sin modificar nada.' },
      { q: 'La variable que determina en qué rutas se buscan los comandos es…', options: ['HOME', 'PATH', 'SHELL', 'PWD'], correct: 1, difficulty: 'Básica', topic: 'Terminal', relatedResource: 'r-so-powershell-bash', explain: 'PATH contiene los directorios donde el intérprete busca los ejecutables que no llevan ruta explícita.' },
      { q: 'Un punto de restauración de Windows…', options: ['copia todos los documentos personales', 'guarda registro y archivos del sistema para deshacer cambios', 'restaura el equipo a fábrica', 'es un backup completo'], correct: 1, difficulty: 'Básica', topic: 'Recuperación', relatedResource: 'r-so-logs-recuperacion', explain: 'Los puntos de restauración cubren configuración del sistema y registro, no datos personales.' },
      { q: 'Tras instalar un controlador de vídeo el equipo no arranca. La secuencia más razonable es…', options: ['reinstalar Windows', 'modo seguro → desinstalar controlador → punto de restauración si persiste', 'cambiar la GPU', 'ejecutar chkdsk'], correct: 1, difficulty: 'Intermedia', topic: 'Recuperación', relatedResource: 'r-so-logs-recuperacion', explain: 'En modo seguro el controlador defectuoso no carga: se desinstala y, si el daño persiste, se restaura al punto previo.' },
      { q: '¿Qué herramienta repara archivos del sistema de Windows?', options: ['sfc /scannow', 'chkdsk /f', 'diskpart', 'msconfig'], correct: 0, difficulty: 'Básica', topic: 'Recuperación', relatedResource: 'r-so-logs-recuperacion', explain: 'System File Checker verifica y repara archivos del sistema; chkdsk actúa sobre el sistema de archivos del disco.' },
      { q: 'El Visor de eventos de Windows registra…', options: ['solo errores críticos', 'eventos con nivel, origen e identificador en registros Sistema/Aplicación', 'únicamente inicios de sesión', 'solo eventos de red'], correct: 1, difficulty: 'Básica', topic: 'Logs', relatedResource: 'r-so-logs-recuperacion', explain: 'Cada evento tiene nivel (info/advertencia/error), origen e ID: la clave para correlacionar con bases de conocimiento.' },
      { q: 'En Linux, journalctl -xe sirve para…', options: ['instalar paquetes', 'ver los últimos registros del sistema con contexto', 'reiniciar servicios', 'montar discos'], correct: 1, difficulty: 'Intermedia', topic: 'Logs', relatedResource: 'r-so-logs-recuperacion', explain: 'journalctl consulta el registro de systemd; -x añade explicaciones y -e salta al final (lo más reciente).' },
      { q: 'Windows 11 exige como mínimo…', options: ['TPM 2.0 + UEFI Secure Boot', 'TPM 1.2 + BIOS legacy', 'solo 4 GB RAM sin TPM', 'GPT sin TPM'], correct: 0, difficulty: 'Básica', topic: 'Instalación', relatedResource: 'r-so-windows', explain: 'Requisito oficial: TPM 2.0, UEFI con Secure Boot, además de CPU compatible y 4 GB de RAM.' },
      { q: 'Un disco de 4 TB en un equipo con BIOS legacy y MBR…', options: ['funciona completo', 'solo se ven 2 TB: MBR direcciona como máximo 2 TB', 'funciona si se formatea FAT32', 'requiere doble partición MBR'], correct: 1, difficulty: 'Intermedia', topic: 'Particiones', relatedResource: 'r-so-particiones', explain: 'MBR usa direcciones de 32 bits LBA con sectores de 512 B: techo de 2 TB. Más capacidad exige GPT (y UEFI para arrancar).' },
      { q: 'Un servicio de Windows que está "Detenido" y en "Manual"…', options: ['arranca solo al reiniciar', 'no arranca salvo que algo lo inicie o lo hagas tú', 'no puede iniciarse nunca', 'arranca al iniciar sesión'], correct: 1, difficulty: 'Intermedia', topic: 'Servicios', relatedResource: 'r-so-procesos', explain: 'Manual significa que no arranca con el sistema; se inicia por demanda (dependencias, disparadores) o manualmente.' },
      { q: '¿Qué comando de Windows fuerza la renovación del lease DHCP?', options: ['ipconfig /renew', 'netsh winsock reset', 'ping -t', 'route add'], correct: 0, difficulty: 'Básica', topic: 'Diagnóstico', relatedResource: 'r-red-icmp-diagnostico', explain: 'ipconfig /release libera y /renew solicita un nuevo lease; winsock reset toca el catálogo de red y exige reinicio.' },
      { q: 'La política de ejecución de PowerShell por defecto…', options: ['permite cualquier script', 'bloquea scripts .ps1 sin firmar (Restricted)', 'solo permite .bat', 'no existe'], correct: 1, difficulty: 'Intermedia', topic: 'PowerShell', relatedResource: 'r-so-powershell-bash', explain: 'Restricted impide ejecutar scripts; se ajusta con Set-ExecutionPolicy según el entorno (RemoteSigned es lo habitual).' },
      { q: 'chmod g+w archivo.sh…', options: ['añade escritura al grupo', 'quita escritura al grupo', 'añade escritura al dueño', 'da permisos totales'], correct: 0, difficulty: 'Básica', topic: 'Permisos', relatedResource: 'r-so-fs-permisos', explain: 'g = grupo, +w = añadir escritura. Es la notación simbólica frente a la octal.' },
      { q: 'Un kill -9 sobre un proceso…', options: ['pide cierre limpio guardando datos', 'termina el proceso inmediatamente sin posibilidad de limpieza', 'solo funciona en Windows', 'reinicia el servicio'], correct: 1, difficulty: 'Intermedia', topic: 'Procesos', relatedResource: 'r-so-memoria', explain: 'SIGKILL (-9) lo mata el kernel sin que el proceso ejecute código de limpieza; TERM (-15) sí pide cierre ordenado.' },
      { q: 'La partición EFI en un equipo UEFI…', options: ['es opcional y se puede borrar', 'contiene los cargadores de arranque (FAT32)', 'es la partición de intercambio', 'solo existe con MBR'], correct: 1, difficulty: 'Intermedia', topic: 'Particiones', relatedResource: 'r-so-arranque', explain: 'La ESP es FAT32 con los bootloaders (Windows Boot Manager, GRUB); borrarla rompe el arranque UEFI.' },
      { q: 'Un equipo arranca en modo seguro pero no en normal. ¿Sospechoso principal?', options: ['CPU dañada', 'controlador o software de terceros que no carga en modo seguro', 'BIOS rota', 'falta de RAM'], correct: 1, difficulty: 'Intermedia', topic: 'Recuperación', relatedResource: 'r-so-logs-recuperacion', explain: 'El modo seguro carga lo mínimo: si ahí funciona, el problema es de controladores o software que solo arranca en modo normal.' },
      { q: 'En Bash, comando1 && comando2…', options: ['ejecuta comando2 siempre', 'ejecuta comando2 solo si comando1 tiene éxito', 'ejecuta ambos en paralelo', 'ejecuta comando2 si comando1 falla'], correct: 1, difficulty: 'Básica', topic: 'Terminal', relatedResource: 'r-so-powershell-bash', explain: '&& encadena en corto-circuito: el segundo solo corre si el primero devuelve éxito (0). || es el caso contrario.' }
    ],
    't-hardware': [
      { q: 'SMT (Hyper-Threading) permite…', options: ['duplicar los núcleos físicos', 'dos hilos por núcleo compartiendo recursos', 'más caché L3', 'más frecuencia'], correct: 1, difficulty: 'Intermedia', topic: 'CPU', relatedResource: 'r-hw-cpu', explain: 'SMT ejecuta dos hilos por núcleo compartiendo unidades de ejecución: mejora ~20-30%, no duplica.' },
      { q: 'Dos procesadores de 3.5 GHz de generaciones distintas…', options: ['rinden igual por tener la misma frecuencia', 'pueden rendir distinto por IPC diferente', 'el antiguo siempre gana', 'depende solo de la RAM'], correct: 1, difficulty: 'Intermedia', topic: 'CPU', relatedResource: 'r-hw-cpu', explain: 'Rendimiento ≈ frecuencia × IPC; cada arquitectura cambia el IPC, así que el mismo GHz no significa el mismo trabajo.' },
      { q: 'El throttling térmico consiste en…', options: ['apagar el equipo', 'reducir la frecuencia al superar la temperatura de seguridad', 'aumentar ventiladores sin límite', 'bloquear el overclock'], correct: 1, difficulty: 'Básica', topic: 'Refrigeración', relatedResource: 'r-hw-psu-refrigeracion', explain: 'Es un mecanismo de protección: baja frecuencia (y rendimiento) para no dañar el silicio.' },
      { q: 'Un equipo rinde bien en frío y cae tras minutos de carga. Primera sospecha…', options: ['RAM defectuosa', 'sistema de refrigeración insuficiente o pasta seca', 'disco lleno', 'fuente sobredimensionada'], correct: 1, difficulty: 'Intermedia', topic: 'Refrigeración', relatedResource: 'r-hw-psu-refrigeracion', explain: 'El patrón "bien → cae con el calor" apunta a térmico: monitorizar temperaturas y frecuencias lo confirma.' },
      { q: 'El doble canal requiere…', options: ['cualquier par de módulos', 'módulos idénticos en ranuras pareadas según el manual', 'memoria ECC', 'frecuencia máxima'], correct: 1, difficulty: 'Básica', topic: 'RAM', relatedResource: 'r-hw-ram', explain: 'El emparejado (tamaño, frecuencia, chips) y las ranuras correctas (A2/B4 habitualmente) activan el doble canal.' },
      { q: 'Mezclas un módulo de 3200 MHz y otro de 2666 MHz. El sistema…', options: ['corre todo a 3200', 'corre todo a 2666 (la menor)', 'no arranca nunca', 'usa 3200 para un módulo y 2666 para otro'], correct: 1, difficulty: 'Intermedia', topic: 'RAM', relatedResource: 'r-hw-ram', explain: 'La memoria corre a la frecuencia común más baja compatible; el perfil se negocia al arrancar.' },
      { q: 'Un SSD NVMe frente a uno SATA se diferencia por…', options: ['el conector M.2 siempre', 'el protocolo sobre PCIe con más colas y velocidad', 'ser más resistente a golpes', 'consumir menos en reposo siempre'], correct: 1, difficulty: 'Intermedia', topic: 'Almacenamiento', relatedResource: 'r-hw-discos', explain: 'Hay SSD M.2 SATA: lo que define a NVMe es el protocolo PCIe, no el formato del conector.' },
      { q: 'Sectores reasignados en crecimiento indican…', options: ['disco sano', 'copia y sustitución planificada del disco', 'falta de TRIM', 'exceso de RAM'], correct: 1, difficulty: 'Intermedia', topic: 'Almacenamiento', relatedResource: 'r-hw-discos', explain: 'El disco está sustituyendo celdas dañadas por reservas: cuando se agotan, falla. Es el aviso clásico del SMART.' },
      { q: 'Al instalar una GPU dedicada, ¿qué revisas de la fuente?', options: ['solo el color del chasis', 'potencia suficiente y conector PCIe de 6/8 pines disponible', 'que sea modular', 'que tenga iluminación'], correct: 1, difficulty: 'Básica', topic: 'PSU', relatedResource: 'r-hw-psu-refrigeracion', explain: 'Sin potencia ni conector dedicado, la GPU no arrancará establemente; los adaptadores dudosos son riesgo.' },
      { q: '80 PLUS Gold en una fuente significa…', options: ['más potencia de salida', 'mayor eficiencia de conversión', 'garantía más larga', 'compatibilidad con GPUs'], correct: 1, difficulty: 'Intermedia', topic: 'PSU', relatedResource: 'r-hw-psu-refrigeracion', explain: 'La certificación mide eficiencia: menos energía perdida en calor. No aumenta la potencia nominal.' },
      { q: 'Presión positiva en el chasis significa…', options: ['más aire sale del que entra', 'más aire entra del que sale (contra el polvo por rendijas)', 'ventiladores al 100%', 'radiador superior'], correct: 1, difficulty: 'Avanzada', topic: 'Refrigeración', relatedResource: 'r-hw-psu-refrigeracion', explain: 'Con entrada dominante, el aire solo entra por los filtros: menos polvo acumulado en placa y componentes.' },
      { q: 'Una placa con chipset H610 y una CPU con socket LGA1700…', options: ['son compatibles si el BIOS soporta esa CPU', 'no son compatibles nunca', 'requieren adaptador', 'depende de la RAM'], correct: 0, difficulty: 'Intermedia', topic: 'Placa base', relatedResource: 'r-hw-componentes', explain: 'Socket correcto es necesario pero no suficiente: el chipset define funcionalidades y el BIOS debe reconocer la CPU.' },
      { q: 'El VRM de una placa base…', options: ['alimenta al procesador con tensión estable', 'controla los ventiladores', 'gestiona el USB', 'es la batería CMOS'], correct: 0, difficulty: 'Intermedia', topic: 'Placa base', relatedResource: 'r-hw-cpu', explain: 'Los VRM convierten 12 V en el voltaje fino que exige la CPU; su calidad afecta a estabilidad y temperaturas.' },
      { q: 'Para 4K a 120 Hz necesitas…', options: ['HDMI 1.4', 'HDMI 2.1 o DisplayPort 1.4+ y cable certificado', 'VGA con adaptador', 'DVI-D dual link'], correct: 1, difficulty: 'Intermedia', topic: 'GPU', relatedResource: 'r-hw-gpu', explain: 'El ancho de banda del enlace (conector + cable) limita antes que la GPU: HDMI 1.4 se queda en 4K30/60 según caso.' },
      { q: 'Artefactos en pantalla solo en juegos (carga) sugieren…', options: ['poca RAM', 'sobrecalentamiento de GPU, alimentación corta o VRAM dañada', 'disco lento', 'monitor viejo'], correct: 1, difficulty: 'Avanzada', topic: 'GPU', relatedResource: 'r-hw-gpu', explain: 'Bajo carga suben consumo y temperatura: es cuando fallan refrigeración, PSU o VRAM. Monitoriza temperaturas y prueba con otra PSU.' },
      { q: 'El PCIe x16 de una GPU…', options: ['alimentación y datos van por el mismo slot siempre', 'transporta datos; la energía extra llega de los conectores PCIe de la fuente', 'es solo para NVMe', 'limita la RAM'], correct: 1, difficulty: 'Intermedia', topic: 'GPU', relatedResource: 'r-hw-gpu', explain: 'El slot entrega hasta 75 W; el resto (a menudo la mayoría) entra por conectores de 6/8 pines desde la PSU.' },
      { q: 'Antes de aplicar pasta térmica nueva…', options: ['limpiar el residuo anterior con alcohol isopropílico', 'mojar el disipador', 'encender el equipo para ablandarla', 'aplicar la mayor cantidad posible'], correct: 0, difficulty: 'Básica', topic: 'Mantenimiento', relatedResource: 'r-man-preventivo', explain: 'Restos de pasta vieja crean puntos de contacto irregulares: se limpia y se aplica una capa fina.' },
      { q: 'La memoria DDR5 frente a DDR4…', options: ['es compatible en las mismas placas', 'cambia voltaje y muesca: exige placa específica', 'es solo para portátiles', 'no aporta ancho de banda'], correct: 1, difficulty: 'Básica', topic: 'RAM', relatedResource: 'r-hw-ram', explain: 'Cada generación DDR cambia la muesca y el voltaje: físicamente no encajan en ranuras de otra generación.' },
      { q: 'Un disco HDD hace "clic" repetitivo y el equipo no arranca. Diagnóstico…', options: ['fallo de RAM', 'daño mecánico del disco: revisar SMART y restaurar desde copia', 'BIOS corrupto', 'cable de vídeo'], correct: 1, difficulty: 'Intermedia', topic: 'Diagnóstico', relatedResource: 'r-hw-discos', explain: 'El "click of death" es fallo de cabezal/motor: el dato se recupera (o no) profesionalmente; lo normal es restaurar backup.' },
      { q: 'Los buses PCIe de una placa se comparten…', options: ['nunca', 'según el chipset: instalar NVMe puede reducir líneas a la GPU x16 → x8', 'solo con GPUs antiguas', 'solo en modo BIOS legacy'], correct: 1, difficulty: 'Avanzada', topic: 'Placa base', relatedResource: 'r-hw-componentes', explain: 'Las líneas las reparte el chipset: la documentación de la placa indica qué slot pierde líneas al ocupar M.2.' },
      { q: 'La memoria cacheada como "en reserva" (hardware reserved) alta suele deberse a…', options: ['RAM rota detectada por POST', 'BIOS antiguo o integrada que mapea memoria', 'demasiado swap', 'modo seguro'], correct: 1, difficulty: 'Avanzada', topic: 'RAM', relatedResource: 'r-hw-ram', explain: 'Actualizaciones de BIOS/UEFI y configuración de la gráfica integrada corrigen reservas anómalas de memoria.' },
      { q: 'CPU-Z informa de la placa, BIOS y RAM. Para temperaturas usarías…', options: ['CPU-Z también', 'HWMonitor/HWiNFO o similar', 'MemTest86', 'CrystalDiskMark'], correct: 1, difficulty: 'Básica', topic: 'Diagnóstico', relatedResource: 'r-hw-cpu', explain: 'CPU-Z identifica; las temperaturas las leen herramientas de sensores como HWMonitor o HWiNFO.' },
      { q: 'Un equipo se apaga solo solo al jugar. Dos sospechosos principales…', options: ['PSU corta en picos y sobrecalentamiento', 'RAM y teclado', 'SSD y monitor', 'BIOS y ratón'], correct: 0, difficulty: 'Intermedia', topic: 'PSU', relatedResource: 'r-hw-psu-refrigeracion', explain: 'El juego maximiza CPU+GPU: si la fuente no da picos o el calor dispara, el equipo se protege apagándose.' },
      { q: 'La pasta térmica conviene renovar…', options: ['cada mes', 'cada 2-3 años o al desmontar el disipador', 'nunca', 'solo en portátiles'], correct: 1, difficulty: 'Básica', topic: 'Mantenimiento', relatedResource: 'r-man-preventivo', explain: 'Se seca y pierde conducción: la renovación periódica devuelve varios grados de margen térmico.' }
    ],
    't-seguridad': [
      { q: 'La diferencia entre phishing y spear phishing es…', options: ['el canal (correo vs SMS)', 'el grado de personalización y dirección a la víctima', 'que el spear phishing es siempre por teléfono', 'que el phishing es legal'], correct: 1, difficulty: 'Intermedia', topic: 'Ingeniería social', relatedResource: 'r-seg-ingenieria-social', explain: 'El spear phishing investiga a la víctima (nombre, cargo, proyectos) y construye un mensaje creíble solo para ella.' },
      { q: 'Un correo del "CEO" pide una transferencia urgente y confidencial. Es…', options: ['normal en contabilidad', 'un caso típico de fraude BEC (Business Email Compromise)', 'phishing masivo', 'spam publicitario'], correct: 1, difficulty: 'Intermedia', topic: 'Ingeniería social', relatedResource: 'r-seg-ingenieria-social', explain: 'El BEC suplanta a directivos por correo; el procedimiento es verificar por otro canal (llamada al número conocido) antes de mover un euro.' },
      { q: 'La principal diferencia entre gusano y troyano es que el gusano…', options: ['necesita un huésped', 'se propaga solo por la red', 'solo roba contraseñas', 'no es malware'], correct: 1, difficulty: 'Básica', topic: 'Malware', relatedResource: 'r-seg-malware', explain: 'El gusano autorreplica sin interacción; el troyano depende de que la víctima lo ejecute creyendo que es legítimo.' },
      { q: 'Un keylogger roba tus credenciales. ¿Qué medida reduce su daño a casi cero?', options: ['antivirus actualizado', 'MFA, porque la contraseña robada no basta para entrar', 'cambiar la contraseña cada semana', 'firewall'], correct: 1, difficulty: 'Intermedia', topic: 'MFA', relatedResource: 'r-seg-contrasenas', explain: 'El segundo factor (app, llave) no viaja por el teclado: aunque el keylogger capture la contraseña, no puede generar el código.' },
      { q: 'Credential stuffing funciona porque…', options: ['los diccionarios son grandes', 'los usuarios reutilizan contraseñas entre servicios', 'el HTTPS es débil', 'los routers son lentos'], correct: 1, difficulty: 'Intermedia', topic: 'Contraseñas', relatedResource: 'r-seg-contrasenas', explain: 'Prueban pares filtrados de un servicio en otros: la reutilización convierte una filtración en muchas cuentas comprometidas.' },
      { q: 'Guardar contraseñas con SHA-256 sin sal es inseguro porque…', options: ['SHA-256 es lento', 'permite tablas precalculadas (rainbow tables) idénticas para todos', 'no se puede implementar', 'necesita clave privada'], correct: 1, difficulty: 'Avanzada', topic: 'Cifrado', relatedResource: 'r-seg-cifrado-wifi', explain: 'Sin sal, dos usuarios con la misma contraseña tienen el mismo hash: se atacan con tablas precalculadas. Con sal + bcrypt/argon2, cada hash es único.' },
      { q: 'El hash de un archivo descargado sirve para…', options: ['cifrarlo', 'verificar que no se alteró durante la descarga', 'comprimirlo', 'firmarlo digitalmente'], correct: 1, difficulty: 'Básica', topic: 'Cifrado', relatedResource: 'r-seg-cifrado-wifi', explain: 'Comparar el hash publicado con el del archivo local confirma integridad (no confidencialidad ni autoría).' },
      { q: 'HTTPS establece la clave de sesión mediante…', options: ['cifrado simétrico solo', 'asimétrico para autenticar y acordar clave, luego simétrico para los datos', 'hash directo de la contraseña', 'WPA3'], correct: 1, difficulty: 'Intermedia', topic: 'Cifrado', relatedResource: 'r-seg-cifrado-wifi', explain: 'El asimétrico autentica al servidor (certificado) y acuerda la clave; el simétrico (rápido) cifra la conversación.' },
      { q: 'Una red Wi-Fi con WEP…', options: ['es segura si la clave es larga', 'está rota desde hace años: debe migrarse a WPA2-AES o WPA3', 'solo es insegura con WPS', 'equivale a WPA3'], correct: 1, difficulty: 'Básica', topic: 'Wi-Fi', relatedResource: 'r-seg-cifrado-wifi', explain: 'WEP se rompe en minutos con herramientas públicas: su existencia hoy es un hallazgo crítico de auditoría.' },
      { q: 'WPA3 mejora a WPA2 principalmente porque…', options: ['usa contraseñas más largas', 'SAE resiste ataques de diccionario y da confidencialidad forward', 'funciona sin contraseña', 'es más rápido'], correct: 1, difficulty: 'Intermedia', topic: 'Wi-Fi', relatedResource: 'r-seg-cifrado-wifi', explain: 'El intercambio SAE evita que capturar el handshake permita atacar la contraseña fuera de línea.' },
      { q: 'El principio de mínimo privilegio dice que…', options: ['todos deben ser administradores para trabajar', 'cada cuenta opera solo con los permisos estrictamente necesarios', 'los permisos se acumulan con el tiempo', 'el admin es el único usuario'], correct: 1, difficulty: 'Básica', topic: 'Buenas prácticas', relatedResource: 'r-seg-contrasenas', explain: 'Limita el radio de daño de un compromiso: una cuenta de usuario normal robada no reconfigura el sistema.' },
      { q: 'La regla 3-2-1 con "1 copia fuera de línea" añade protección contra…', options: ['fallos del disco solamente', 'ransomware que cifra también las copias conectadas', 'robo del portátil', 'ingeniería social'], correct: 1, difficulty: 'Intermedia', topic: 'Backups', relatedResource: 'r-seg-backup', explain: 'Una copia desconectada (o inmutable) no puede ser cifrada por el ransomware: es la que permite recuperar sin pagar.' },
      { q: 'Tras clicar un enlace de phishing y escribir tus credenciales, la primera acción es…', options: ['apagar el equipo', 'cambiar esa contraseña y activar/revisar MFA, y avisar si es un entorno de trabajo', 'borrar el correo', 'esperar a ver si pasa algo'], correct: 1, difficulty: 'Intermedia', topic: 'Ingeniería social', relatedResource: 'r-seg-ingenieria-social', explain: 'La ventana de abuso es minutos: cambiar credenciales (empezando si la reutilizaste) y reportar limita el daño.' },
      { q: 'Un antivirus heurístico…', options: ['compara solo firmas conocidas', 'analiza comportamientos sospechosos de programas desconocidos', 'cifra el disco', 'sustituye al firewall'], correct: 1, difficulty: 'Intermedia', topic: 'Malware', relatedResource: 'r-seg-malware', explain: 'Las firmas cubren lo conocido; la heurística detecta patrones de comportamiento (cifrado masivo, inyecciones) de amenazas nuevas.' },
      { q: 'En una red doméstica, separar IoT (cámaras, TVs) en otra VLAN o SSID sirve para…', options: ['darles más velocidad', 'contener un dispositivo comprometido lejos de tus equipos y datos', 'ahorrar energía', 'mejorar el ping en juegos'], correct: 1, difficulty: 'Avanzada', topic: 'Wi-Fi', relatedResource: 'r-red-vlan', explain: 'El IoT suele ser lo menos actualizado y más expuesto: si se compromete, la segmentación evita que pivote a tu red principal.' },
      { q: 'El spam es principalmente…', options: ['un tipo de malware', 'correo no solicitado en masa (con o sin intención maliciosa)', 'un protocolo', 'un firewall'], correct: 1, difficulty: 'Básica', topic: 'Buenas prácticas', relatedResource: 'r-seg-ingenieria-social', explain: 'El spam es correo masivo no solicitado; puede ser publicidad o vehículo de phishing, pero no es malware por sí mismo.' },
      { q: 'La autenticación 802.1X en Wi-Fi Enterprise significa…', options: ['una contraseña compartida entre todos', 'credenciales individuales validadas por un servidor RADIUS', 'sin cifrado', 'solo para invitados'], correct: 1, difficulty: 'Avanzada', topic: 'Wi-Fi', relatedResource: 'r-seg-cifrado-wifi', explain: 'Cada usuario se autentica ante RADIUS: se pueden revocar cuentas individualmente y auditar quién se conectó.' },
      { q: 'Ante un posible brote de ransomware en la oficina, el primer paso es…', options: ['reiniciar todos los equipos', 'aislar de la red los equipos afectados y contener', 'pagar el rescate', 'abrir los archivos para ver el daño'], correct: 1, difficulty: 'Intermedia', topic: 'Malware', relatedResource: 'r-seg-malware', explain: 'El cifrado se propaga por recursos de red: aislar (desconectar) limita el alcance antes de analizar o restaurar.' },
      { q: 'El vishing es…', options: ['phishing por SMS', 'suplantación por llamada telefónica', 'spam en redes sociales', 'un tipo de firewall'], correct: 1, difficulty: 'Básica', topic: 'Ingeniería social', relatedResource: 'r-seg-ingenieria-social', explain: 'Vishing = voice phishing: llamadas que suplantan bancos o soporte técnico; smishing es la variante por SMS.' },
      { q: 'Un certificado con candado en el navegador garantiza…', options: ['que la web es legítima y de confianza', 'cifrado del canal y que el dominio coincide con el certificado', 'que no hay phishing posible', 'que el servidor está en tu país'], correct: 1, difficulty: 'Intermedia', topic: 'Cifrado', relatedResource: 'r-seg-cifrado-wifi', explain: 'El candado (TLS válido) cifra y autentica el dominio, pero los sitios de phishing también usan HTTPS: el candado no es sello de honestidad.' },
      { q: 'La confidencialidad forward (perfect forward secrecy) significa…', options: ['las claves antiguas no descifran sesiones pasadas si se comprometen', 'las sesiones nunca terminan', 'el servidor guarda todas las claves', 'solo aplica a Wi-Fi'], correct: 1, difficulty: 'Avanzada', topic: 'Cifrado', relatedResource: 'r-seg-cifrado-wifi', explain: 'Con PFS cada sesión usa claves efímeras: robar la clave del servidor hoy no permite descifrar capturas antiguas.' },
      { q: '¿Qué práctica reduce el impacto de credential stuffing en un portal web?', options: ['bloquear usuarios tras N intentos + detección de listas filtradas', 'permitir contraseñas de 4 caracteres', 'guardar contraseñas con MD5', 'avisar por SMS el usuario'], correct: 0, difficulty: 'Avanzada', topic: 'Contraseñas', relatedResource: 'r-seg-contrasenas', explain: 'Limitar intentos, usar listas de filtraciones (have I been pwned style) y MFA corta el ataque automatizado.' },
      { q: 'La ingeniería social se basa en…', options: ['explotar fallos de software', 'manipular a las personas (urgencia, autoridad, miedo)', 'fuerza bruta matemática', 'vulnerabilidades del router'], correct: 1, difficulty: 'Básica', topic: 'Ingeniería social', relatedResource: 'r-seg-ingenieria-social', explain: 'Ataca el eslabón humano: las emociones provocan acciones sin verificación. El antídoto es procedimiento y freno.' },
      { q: 'Un gusano que se propaga por USB aprovecha…', options: ['el protocolo USB mismo', 'la autorreproducción automática y la curiosidad del usuario', 'el firewall', 'WPA3'], correct: 1, difficulty: 'Intermedia', topic: 'Malware', relatedResource: 'r-seg-malware', explain: 'Históricamente autorun y hoy la curiosidad (abrir "lo que aparece"): los USB encontrados no se conectan jamás.' },
      { q: 'La mejor defensa ante phishing en una organización es…', options: ['solo el antivirus', 'formación + simulacros + MFA + filtrado de correo combinados', 'prohibir el correo', 'confiar en el buen ojo de todos'], correct: 1, difficulty: 'Intermedia', topic: 'Buenas prácticas', relatedResource: 'r-seg-ingenieria-social', explain: 'Es defensa en profundidad: reducir los que llegan (filtrado), los que caen (formación) y su daño (MFA).' }
    ]
  };

  /* ---------- Tests nuevos ---------- */

  const NEW_TESTS = [
    {
      id: 't-virtualizacion',
      title: 'Test de Virtualización',
      category: 'Virtualización',
      desc: 'Hipervisores, máquinas virtuales, snapshots y redes virtuales.',
      questions: [
        { q: 'Un hipervisor de tipo 1…', options: ['se instala sobre un SO anfitrión', 'corre directamente sobre el hardware', 'solo existe en la nube', 'es un emulador de CPU'], correct: 1, difficulty: 'Básica', topic: 'Hipervisores', relatedResource: 'r-virt-conceptos', explain: 'Tipo 1 (bare-metal): ESXi, Hyper-V. Tipo 2 (VirtualBox) necesita un sistema anfitrión.' },
        { q: 'VirtualBox es un hipervisor…', options: ['tipo 1', 'tipo 2', 'bare-metal', 'de contenedores'], correct: 1, difficulty: 'Básica', topic: 'Hipervisores', relatedResource: 'r-virt-virtualbox', explain: 'Se instala como aplicación sobre Windows/Linux/macOS: tipo 2.' },
        { q: 'Asignas 15,5 GB de RAM a una VM en un anfitrión con 16 GB. Problema…', options: ['ninguno', 'el anfitrión se queda sin memoria y puede colapsar todo', 'la VM va más rápida', 'el disco se llena'], correct: 1, difficulty: 'Intermedia', topic: 'Recursos', relatedResource: 'r-virt-virtualbox', explain: 'El anfitrión también necesita memoria (kernel, apps): regla práctica es dejar 4 GB o el 25% libres.' },
        { q: 'Un snapshot de VirtualBox…', options: ['es un backup exportable de la VM completa', 'guarda el estado del disco en ese momento para poder volver', 'copia la RAM a un archivo ISO', 'es obligatorio antes de apagar'], correct: 1, difficulty: 'Básica', topic: 'Snapshots', relatedResource: 'r-virt-virtualbox', explain: 'Congela el estado del disco (delta); no sustituye a exportar/clonar la máquina.' },
        { q: 'En modo NAT, una VM…', options: ['es visible desde la red local', 'sale a internet detrás del NAT del hipervisor sin ser visible', 'no tiene red', 'usa la MAC del anfitrión'], correct: 1, difficulty: 'Básica', topic: 'Redes virtuales', relatedResource: 'r-virt-virtualbox', explain: 'El hipervisor hace de router-NAT: la VM sale, pero nadie desde la LAN puede iniciar conexiones hacia ella.' },
        { q: 'Para que una VM de laboratorio sea accesible desde otro equipo físico de la LAN, el modo adecuado es…', options: ['NAT', 'puente (bridge)', 'host-only', 'red interna'], correct: 1, difficulty: 'Intermedia', topic: 'Redes virtuales', relatedResource: 'r-virt-redes', explain: 'El puente conecta la VM al switch físico como un equipo más: IP de la LAN y accesible desde fuera.' },
        { q: 'La diferencia entre host-only y red interna es…', options: ['ninguna', 'host-only permite acceso al anfitrión; la red interna aísla incluso de él', 'la interna es más rápida', 'host-only usa Wi-Fi'], correct: 1, difficulty: 'Avanzada', topic: 'Redes virtuales', relatedResource: 'r-virt-redes', explain: 'Host-only: VM ↔ anfitrión. Interna: VM ↔ VM, sin anfitrión: aislamiento máximo.' },
        { q: 'Una VM con dos tarjetas de red (interna A + interna B) y reenvío IP activado actúa como…', options: ['switch de capa 2', 'router entre ambas redes', 'firewall de capa 7', 'punto de acceso'], correct: 1, difficulty: 'Intermedia', topic: 'Laboratorios', relatedResource: 'r-virt-redes', explain: 'Con ip_forward y rutas en los clientes, esa VM enruta paquetes entre las dos redes internas: laboratorio de routing clásico.' },
        { q: 'La sobreasignación de vCPU funciona si…', options: ['nunca funciona', 'las cargas no alcanzan el pico a la vez', 'el hipervisor es tipo 2', 'hay NVMe'], correct: 1, difficulty: 'Intermedia', topic: 'Recursos', relatedResource: 'r-virt-conceptos', explain: 'Sobreasignar (más vCPU que núcleos) aprovecha que no todos trabajan a la vez; si todos pican, hay contención.' },
        { q: 'Las Guest Additions/VMware Tools aportan…', options: ['licencia del sistema invitado', 'drivers de vídeo, portapapeles compartido y sincronización de reloj', 'un segundo SO', 'antivirus'], correct: 1, difficulty: 'Básica', topic: 'Máquinas virtuales', relatedResource: 'r-virt-virtualbox', explain: 'Son los drivers paravirtualizados que mejoran gráficos, integración (portapapeles, drag&drop) y gestión.' },
        { q: 'Un disco virtual de crecimiento dinámico…', options: ['ocupa desde el principio todo su tamaño', 'crece al escribirse hasta su máximo', 'se comprime automáticamente', 'no admite snapshots'], correct: 1, difficulty: 'Básica', topic: 'Discos virtuales', relatedResource: 'r-virt-conceptos', explain: 'Reserva lógica máxima pero ocupación física creciente; conviene compactarlo periódicamente.' },
        { q: 'Virtualizar un aula de 30 equipos con 30 VMs en un servidor físico exige sobre todo…', options: ['mucho almacenamiento y RAM en el servidor, y plantillas', '30 teclados', 'WPA3', 'un switch de 30 puertos'], correct: 0, difficulty: 'Intermedia', topic: 'Casos de uso', relatedResource: 'r-virt-conceptos', explain: 'Cada VM consume RAM y disco: con plantilla base + discos diferenciales el ahorro es enorme.' },
        { q: 'Restaurar un snapshot…', options: ['elimina cambios posteriores a su creación', 'une los cambios con el estado actual', 'formatea el disco virtual', 'actualiza el SO invitado'], correct: 0, difficulty: 'Básica', topic: 'Snapshots', relatedResource: 'r-virt-virtualbox', explain: 'Vuelve al estado congelado: todo lo hecho después desaparece (por eso se toma antes de la prueba).' },
        { q: 'Clonar una VM frente a copiar sus archivos sirve para…', options: ['nada, es lo mismo', 'obtener identidad única (MAC, SID) evitando conflictos en la red', 'ahorrar RAM', 'cambiar el hipervisor'], correct: 1, difficulty: 'Avanzada', topic: 'Máquinas virtuales', relatedResource: 'r-virt-conceptos', explain: 'Copiar a lo burro duplica MAC/SID: dos equipos "idénticos" chocan en la red. La clonación regenera identidad.' },
        { q: 'En un laboratorio de 3 redes internas, el equipo que las une necesita…', options: ['una tarjeta por red y routing activado', 'un solo adaptador Wi-Fi', 'un hub virtual', 'WPA3'], correct: 0, difficulty: 'Intermedia', topic: 'Laboratorios', relatedResource: 'r-virt-redes', explain: 'Un router virtual: una interfaz por red + ip_forward + rutas en los clientes.' },
        { q: 'Un Snapshot encadenado (árbol de snapshots)…', options: ['mejora el rendimiento al crecer', 'degrada el rendimiento al alargarse la cadena', 'es un backup válido para producción', 'no se puede borrar'], correct: 1, difficulty: 'Avanzada', topic: 'Snapshots', relatedResource: 'r-virt-virtualbox', explain: 'Cada snapshot añade una capa delta: cuanta más cadena, más saltos al leer. Se consolidan periódicamente.' },
        { q: 'Para pruebas de malware controladas, la configuración más segura es…', options: ['NAT con antivirus en la VM', 'red interna sin salida, snapshot limpio y restauración posterior', 'puente con firewall', 'host-only con internet'], correct: 1, difficulty: 'Avanzada', topic: 'Laboratorios', relatedResource: 'r-virt-redes', explain: 'Aislamiento total (interna sin salida) + snapshot: el malware no escapa y el estado se destruye al restaurar.' },
        { q: 'La diferencia entre VM y contenedor es que el contenedor…', options: ['virtualiza hardware completo con su kernel', 'comparte el kernel del anfitrión y empaqueta app + dependencias', 'es más pesado', 'no se puede limitar de recursos'], correct: 1, difficulty: 'Intermedia', topic: 'Conceptos', relatedResource: 'r-virt-conceptos', explain: 'El contenedor no lleva kernel propio: arranca en milisegundos y es más ligero; la VM aísla más.' }
      ]
    },
    {
      id: 't-mantenimiento',
      title: 'Test de Mantenimiento',
      category: 'Mantenimiento',
      desc: 'Preventivo, diagnóstico, temperaturas, SMART y recuperación de averías.',
      questions: [
        { q: 'El mantenimiento preventivo se caracteriza por…', options: ['actuar tras la avería', 'tareas programadas que reducen fallos futuros', 'sustituir todo cada año', 'solo limpiar el teclado'], correct: 1, difficulty: 'Básica', topic: 'Preventivo', relatedResource: 'r-man-preventivo', explain: 'Calendario + checklist (polvo, temperaturas, SMART, espacio, backups): prevenir es más barato que reparar.' },
        { q: 'Para limpiar el interior de un PC no debes usar…', options: ['aire comprimido', 'brocha antiestática', 'aspiradora doméstica directa', 'algodón en disipadores'], correct: 2, difficulty: 'Básica', topic: 'Limpieza', relatedResource: 'r-man-preventivo', explain: 'La aspiradora genera estática y puede arrancar componentes; se usa aire comprimido sujetando ventiladores.' },
        { q: 'La pasta térmica seca provoca…', options: ['menos consumo', 'subida de temperaturas y throttling', 'pérdida de datos', 'ruido de disco'], correct: 1, difficulty: 'Básica', topic: 'Temperaturas', relatedResource: 'r-man-preventivo', explain: 'Pierde conducción térmica: la CPU se calienta más y el sistema reduce frecuencia para protegerse.' },
        { q: 'Un valor SMART de "sectores reasignados" creciente significa…', options: ['disco óptimo', 'celdas dañadas sustituidas por reservas: planificar sustitución', 'falta TRIM', 'demasiados archivos'], correct: 1, difficulty: 'Intermedia', topic: 'SMART', relatedResource: 'r-hw-discos', explain: 'Es el indicador clásico de fin de vida: cuando las reservas se agotan, aparecen sectores ilegibles.' },
        { q: 'El método profesional de diagnóstico empieza por…', options: ['formatear', 'recoger síntomas y qué cambió recientemente', 'cambiar la fuente', 'desmontar todo'], correct: 1, difficulty: 'Básica', topic: 'Diagnóstico', relatedResource: 'r-man-diagnostico', explain: 'Información primero: qué pasó, cuándo, qué se instaló. A partir de ahí, hipótesis y pruebas ordenadas.' },
        { q: 'Cambiar tres componentes a la vez y que funcione…', options: ['es el método más rápido', 'impide saber qué era: hay que aislar un cambio cada vez', 'demuestra que era la placa', 'no pasa nada'], correct: 1, difficulty: 'Intermedia', topic: 'Diagnóstico', relatedResource: 'r-man-diagnostico', explain: 'Sin variable única no hay diagnóstico: se cambia y se prueba, de lo general a lo específico.' },
        { q: 'Un BSOD con código MEMORY_MANAGEMENT apunta primero a…', options: ['disco', 'RAM o driver de memoria', 'teclado', 'monitor'], correct: 1, difficulty: 'Intermedia', topic: 'Averías', relatedResource: 'r-so-logs-recuperacion', explain: 'El código orienta: memoria (RAM defectuosa, overclock, driver). MemTest86 y desactivar overclock son primeros pasos.' },
        { q: 'El equipo arranca en modo seguro pero no normal. Sospechoso…', options: ['hardware base', 'controladores o software de terceros', 'BIOS', 'pila CMOS'], correct: 1, difficulty: 'Intermedia', topic: 'Averías', relatedResource: 'r-so-logs-recuperacion', explain: 'El modo seguro carga lo mínimo: si ahí funciona, el fallo vive en lo que no carga (drivers, autostart).' },
        { q: 'Temperatura de CPU en carga sostenida por encima de 95 °C indica…', options: ['normalidad', 'problema de refrigeración (pasta, disipador, flujo) que debe atenderse', 'PSU potente', 'RAM en doble canal'], correct: 1, difficulty: 'Intermedia', topic: 'Temperaturas', relatedResource: 'r-hw-psu-refrigeracion', explain: 'Valores de referencia en carga: CPU < ~85 °C. Por encima: revisar montaje, pasta y ventilación antes de dañar el chip.' },
        { q: 'El orden razonable ante "no enciende" es…', options: ['enchufe/cable → fuente (pines, interruptor) → botón/panel → placa', 'placa → CPU → RAM → fuente', 'reinstalar Windows', 'cambiar monitor'], correct: 0, difficulty: 'Intermedia', topic: 'Diagnóstico', relatedResource: 'r-man-diagnostico', explain: 'De lo general y barato a lo específico: alimentación primero, ya que sin ella nada más se puede probar.' },
        { q: 'Un punto de restauración…', options: ['borra tus documentos', 'deshace cambios del sistema sin tocar datos personales', 'formatea C:', 'actualiza drivers'], correct: 1, difficulty: 'Básica', topic: 'Recuperación', relatedResource: 'r-so-logs-recuperacion', explain: 'Guarda registro y archivos de sistema: es el paso intermedio entre reparar y reinstalar.' },
        { q: 'Antes de actualizar el BIOS/UEFI se recomienda…', options: ['nada especial', 'conocer modelo exacto, SAI/SAI o batería llena y leer las notas del fabricante', 'borrar la partición EFI', 'quitar la RAM'], correct: 1, difficulty: 'Intermedia', topic: 'Firmware', relatedResource: 'r-man-drivers', explain: 'Un flasheo interrumpido puede dejar la placa muerta: corriente estable y archivo correcto son imprescindibles.' },
        { q: 'Un SSD con TRIM desactivado…', options: ['no nota nada', 'degrada su velocidad de escritura con el tiempo', 'pierde datos al apagar', 'aumenta su vida útil'], correct: 1, difficulty: 'Intermedia', topic: 'Almacenamiento', relatedResource: 'r-hw-discos', explain: 'Sin TRIM, el SSD no sabe qué bloques están libres: las escrituras se hacen más lentas (write amplification).' },
        { q: 'La regla de oro ante cualquier intervención es…', options: ['instalar rápido', 'copia de seguridad previa y documentar lo hecho', 'formatear por si acaso', 'probar solo en producción'], correct: 1, difficulty: 'Básica', topic: 'Preventivo', relatedResource: 'r-man-preventivo', explain: 'Backup antes de tocar y registro después: la documentación es la memoria del mantenimiento.' },
        { q: 'El POST se completa pero no hay imagen. Primeras comprobaciones…', options: ['monitor/cable y GPU (o RAM integrada si existe)', 'disco y Windows', 'teclado y ratón', 'fuente nueva directamente'], correct: 0, difficulty: 'Intermedia', topic: 'Averías', relatedResource: 'r-man-montaje', explain: 'Si hay POST, el corazón funciona: la cadena vídeo (monitor, cable, GPU, RAM) es el siguiente eslabón.' },
        { q: 'Un equipo de aula con 5 años sin mantenimiento probablemente presente…', options: ['menos polvo', 'polvo acumulado, pasta seca y ventiladores ruidosos', 'BIOS nuevo', 'SMART perfecto'], correct: 1, difficulty: 'Básica', topic: 'Preventivo', relatedResource: 'r-man-preventivo', explain: 'Es el perfil clásico: limpieza + pasta + revisión de ventiladores devuelve rendimiento y silencio.' },
        { q: 'El registro de eventos dice "Disk error 7" repetido. Acción…', options: ['ignorar', 'revisar SMART y estado del cable/SATA, con copia inmediata', 'desfragmentar', 'cambiar el antivirus'], correct: 1, difficulty: 'Avanzada', topic: 'Logs', relatedResource: 'r-hw-discos', explain: 'Errores de disco en el visor + SMART = copia YA y plan de sustitución; cada arranque es una lotería.' },
        { q: 'Tras un apagón, el equipo no arranca y huele a quemado. Primera acción…', options: ['encender de nuevo para probar', 'desconectar y no alimentar: revisar fuente y olores localizados', 'formatear', 'cambiar el SSD'], correct: 1, difficulty: 'Intermedia', topic: 'Averías', relatedResource: 'r-man-diagnostico', explain: 'Alimentar de nuevo con un cortocircuito puede multiplicar el daño: se revisa fuente y componentes con el equipo sin corriente.' }
      ]
    },
    {
      id: 't-ofimatica',
      title: 'Test de Ofimática',
      category: 'Ofimática',
      desc: 'Documentos, hojas de cálculo, presentaciones y formatos.',
      questions: [
        { q: 'La ventaja real de usar estilos en un procesador de textos es…', options: ['el documento pesa menos', 'formato centralizado: cambiar el estilo actualiza todo el documento e índices', 'imprime mejor', 'evita la nube'], correct: 1, difficulty: 'Básica', topic: 'Documentos', relatedResource: 'r-ofi-texto', explain: 'El índice, los numerados y la apariencia se gobiernan desde los estilos: un cambio, cero retoques manuales.' },
        { q: 'Un índice automático se construye a partir de…', options: ['párrafos en negrita', 'los niveles de título (Título 1, 2…) aplicados en el texto', 'marcadores manuales', 'los saltos de página'], correct: 1, difficulty: 'Básica', topic: 'Documentos', relatedResource: 'r-ofi-texto', explain: 'Sin estilos de título no hay índice automático posible: es su materia prima.' },
        { q: 'La referencia $B$4 en una hoja de cálculo es…', options: ['relativa', 'absoluta: no cambia al copiar la fórmula', 'un error de sintaxis', 'mixta por columnas'], correct: 1, difficulty: 'Básica', topic: 'Hojas de cálculo', relatedResource: 'r-ofi-hoja', explain: 'Los $ fijan columna y fila. $B4 fija solo columna; B$4 solo fila (mixtas).' },
        { q: 'Copias =A1*$C$1 de la fila 1 a la fila 10. En la fila 10 queda…', options: ['=A10*$C$10', '=A10*$C$1', '=A1*$C$1', '=A10*C1'], correct: 1, difficulty: 'Intermedia', topic: 'Hojas de cálculo', relatedResource: 'r-ofi-hoja', explain: 'La relativa se desplaza (A1→A10); la absoluta permanece ($C$1).' },
        { q: 'Para un gráfico que muestra la evolución de ventas mensuales usarías…', options: ['pastel', 'líneas', 'anillo', 'dispersión 3D'], correct: 1, difficulty: 'Básica', topic: 'Hojas de cálculo', relatedResource: 'r-ofi-hoja', explain: 'Las series temporales se leen mejor en líneas; el pastel se reserva a proporciones de un todo puntual.' },
        { q: 'El formato CSV…', options: ['guarda fórmulas y formatos', 'almacena solo datos separados por un delimitador', 'es exclusivo de Excel', 'no abre en LibreOffice'], correct: 1, difficulty: 'Básica', topic: 'Formatos', relatedResource: 'r-ofi-hoja', explain: 'CSV es texto plano universal: pierde fórmulas y formato, gana compatibilidad total.' },
        { q: 'La ventaja de PDF al compartir documentos es…', options: ['se puede editar fácil', 'maquetación fija y portable: se ve igual en cualquier equipo', 'ocupa menos que todo', 'permite macros'], correct: 1, difficulty: 'Básica', topic: 'Formatos', relatedResource: 'r-ofi-presentaciones', explain: 'PDF congela la apariencia: ideal para imprimir o distribuir sin sorpresas de fuentes y versiones.' },
        { q: 'Un archivo .docx frente a .odt…', options: ['no tienen diferencia', 'son formatos de procesador distintos (Office vs OpenDocument) con compatibilidad amplia hoy', 'solo abre en Windows', 'es el mismo formato con otro nombre'], correct: 1, difficulty: 'Intermedia', topic: 'Formatos', relatedResource: 'r-ofi-texto', explain: 'DOCX es el formato OOXML de Microsoft; ODT el OpenDocument. Las suites actuales abren ambos con matices de maquetación.' },
        { q: 'El límite práctico de FAT32 que afecta a ofimática es…', options: ['4 GB por archivo: impide copiar vídeos/ISOs a un USB FAT32', '2 TB por carpeta', '100 archivos', 'no hay límite'], correct: 0, difficulty: 'Intermedia', topic: 'Formatos', relatedResource: 'r-so-particiones', explain: 'Por eso los USB de gran tamaño se formatean en exFAT: sin ese límite y compatible con Windows/Mac.' },
        { q: 'En una presentación de 10 minutos, el número razonable de diapositivas es…', options: ['2', '8-10, una idea por diapositiva', '30 con todo el texto', '1 con todo'], correct: 1, difficulty: 'Básica', topic: 'Presentaciones', relatedResource: 'r-ofi-presentaciones', explain: 'Regla orientativa 1 diapositiva/minuto: el detalle lo pone el orador, no el texto en pantalla.' },
        { q: 'El patrón de diapositivas sirve para…', options: ['añadir animaciones', 'unificar tipografía, colores y logotipo en toda la presentación', 'exportar a PDF', 'imprimir folletos'], correct: 1, difficulty: 'Básica', topic: 'Presentaciones', relatedResource: 'r-ofi-presentaciones', explain: 'Cambiar el patrón actualiza todas las diapositivas: coherencia visual sin retoques una a una.' },
        { q: 'La validación de datos en una hoja evita…', options: ['fórmulas lentas', 'entradas erróneas (fuera de rango, lista cerrada) en la captura', 'el autoguardado', 'los gráficos'], correct: 1, difficulty: 'Intermedia', topic: 'Hojas de cálculo', relatedResource: 'r-ofi-hoja', explain: 'Restringe lo que se puede escribir en una celda: menos limpieza posterior y menos errores de fórmula.' },
        { q: 'El formato condicional sirve para…', options: ['proteger celdas', 'resaltar automáticamente celdas según su valor (umbral, duplicados…)', 'ordenar columnas', 'imprimir a color'], correct: 1, difficulty: 'Intermedia', topic: 'Hojas de cálculo', relatedResource: 'r-ofi-hoja', explain: 'Aplica formato según reglas: es la manera rápida de ver avisos (rojos) sin revisar dato a dato.' },
        { q: 'Para que un documento largo se navegue por el panel de navegación necesitas…', options: ['muchas páginas', 'aplicar estilos de título', 'hipervínculos manuales', 'insertar sumario'], correct: 1, difficulty: 'Intermedia', topic: 'Documentos', relatedResource: 'r-ofi-texto', explain: 'El panel lee los mismos estilos de título: estructura navegable gratis si el documento está bien maquetado.' },
        { q: 'La separación correcta de datos y presentación en una hoja implica…', options: ['colores para cada dato', 'una hoja de datos limpios y otra de informe/formulario que la referencia', 'todo en A1', 'ocultar fórmulas'], correct: 1, difficulty: 'Avanzada', topic: 'Hojas de cálculo', relatedResource: 'r-ofi-hoja', explain: 'Datos crudos en una pestaña, informe en otra: las fórmulas apuntan a datos y nunca se mezclan con decoración.' },
        { q: 'Antes de enviar un documento final conviene…', options: ['exportar a PDF y revisar numeración/índice actualizado', 'enviar el .docx siempre', 'borrar los estilos', 'guardar en el escritorio'], correct: 0, difficulty: 'Intermedia', topic: 'Documentos', relatedResource: 'r-ofi-texto', explain: 'PDF congela lo que ves; actualizar campos (índice, numeración) antes evita sorpresas de versión.' }
      ]
    },

    /* ---- Fase 6C: los 4 bancos que vivían en EXTRA_QUESTIONS pero sin test ----
       Se declaran aquí, vacíos, para que merge() los rellene desde EXTRA_QUESTIONS
       conservando el orden original. NO se duplica ninguna pregunta: el banco
       sigue siendo la única fuente. La descripción resume los topics reales del
       banco; no inventa temario. Categorías ya existentes en SMR_DATA.categories. */
    {
      id: 't-redes',
      title: 'Test de Redes',
      category: 'Redes',
      desc: 'Subnetting, Ethernet, VLAN, NAT, routing, diagnóstico, DNS, IPv6, medios y VLSM.',
      questions: []
    },
    {
      id: 't-sistemas',
      title: 'Test de Sistemas Operativos',
      category: 'Sistemas Operativos',
      desc: 'Permisos, memoria, procesos, arranque, servicios, terminal, recuperación, logs, instalación y particiones.',
      questions: []
    },
    {
      id: 't-hardware',
      title: 'Test de Hardware',
      category: 'Hardware',
      desc: 'CPU, refrigeración, RAM, almacenamiento, PSU, placa base, GPU, mantenimiento y diagnóstico.',
      questions: []
    },
    {
      id: 't-seguridad',
      title: 'Test de Seguridad',
      category: 'Seguridad',
      desc: 'Ingeniería social, malware, MFA, contraseñas, cifrado, Wi-Fi, buenas prácticas y copias de seguridad.',
      questions: []
    }
  ];

  /* ---------- Fusión y validación ---------- */

  const problems = [];

  function merge() {
    /* 1) Registrar los tests declarados en NEW_TESTS ANTES de volcar los bancos.
          Antes se hacia al reves: EXTRA_QUESTIONS se procesaba primero, sus tests
          destino no existian todavia y sus 102 preguntas se descartaban.
          Reordenar no altera los tests ya existentes: ninguno de ellos es destino
          de EXTRA_QUESTIONS y sus preguntas siguen llegando por su propia via. */
    const knownTests = new Set(D.tests.map((t) => t.id));
    (NEW_TESTS || []).forEach((t) => {
      if (knownTests.has(t.id)) return;
      D.tests.push(t);
      knownTests.add(t.id);
    });

    /* 2) Volcar cada banco en su test, respetando el orden original del array. */
    Object.keys(EXTRA_QUESTIONS || {}).forEach((testId) => {
      const test = D.tests.find((t) => t.id === testId);
      if (!test) { problems.push('test inexistente para preguntas extra: ' + testId); return; }
      const seen = new Set(test.questions.map((q) => q.q));
      (EXTRA_QUESTIONS[testId] || []).forEach((q) => {
        if (seen.has(q.q)) return;
        test.questions.push(q);
        seen.add(q.q);
      });
    });

    /* 3) Normalizar relatedResource.
          Una referencia que no resuelve se ANULA (null) en lugar de quedarse rota.
          No se sustituye por ningun otro recurso: no existe evidencia interna que
          permita elegir un equivalente, y un id inventado seria peor que ninguno.
          El valor original se conserva intacto en EXTRA_QUESTIONS/NEW_TESTS para
          que la decision sea reversible y auditable.
          relatedResource no participa en la clave SRS (testId:qIndex), asi que
          anularlo no altera el progreso ni el historial de repaso. */
    const resIdsAudit = new Set((D.resources || []).map((r) => r.id));
    let anuladas = 0;
    D.tests.forEach((t) => {
      t.questions.forEach((q) => {
        if (!q.relatedResource) return;
        if (resIdsAudit.has(q.relatedResource)) return;
        q.relatedResource = null;
        anuladas++;
      });
    });
    if (anuladas && window.console) {
      console.info('[SMR questions] ' + anuladas + ' relatedResource anulado(s): el recurso de destino no existe.');
    }

    /* Validación del banco completo */
    const DIFFS = ['Básica', 'Intermedia', 'Avanzada'];
    const resIds = new Set((D.resources || []).map((r) => r.id));
    const questionSeen = new Set();
    D.tests.forEach((t) => {
      t.questions.forEach((q, i) => {
        const key = t.id + '::' + q.q;
        if (questionSeen.has(key)) problems.push('pregunta duplicada en ' + t.id + ': ' + q.q.slice(0, 50));
        questionSeen.add(key);
        if (!Array.isArray(q.options) || q.options.length < 2) problems.push(t.id + '[' + i + '] opciones insuficientes');
        else if (typeof q.correct !== 'number' || q.correct < 0 || q.correct >= q.options.length) problems.push(t.id + '[' + i + '] índice correct inválido');
        if (!q.explain) problems.push(t.id + '[' + i + '] sin explicación');
        if (!DIFFS.includes(q.difficulty)) problems.push(t.id + '[' + i + '] dificultad inválida: ' + q.difficulty);
        if (q.relatedResource && !resIds.has(q.relatedResource)) problems.push(t.id + '[' + i + '] relatedResource inexistente: ' + q.relatedResource);
      });
    });

    if (problems.length && window.console) {
      window.console.warn('[SMR questions] ' + problems.length + ' aviso(s) de validación:', problems.slice(0, 10));
    }
  }

  merge();
})();
